baseURL = 'https://bl9.github.io/'
languageCode = 'en-us'
title = 'Bl9 Rambling'
theme = 'hugo-ficurini'

[outputs]
  home = ['HTML', 'RSS', 'JSON']
  section = ['HTML', 'RSS']

[params]
  rssLimit = 20
